apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cis-webhook.field.vmware.com.0.0.0
  annotations:
    kapp.k14s.io/delete-strategy: orphan
spec:
  refName: cis-webhook.field.vmware.com
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: null
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: cis-webhook.field.vmware.com
  annotations:
    kapp.k14s.io/delete-strategy: orphan
spec:
  displayName: cis-webhook
  longDescription: cis-webhook.field.vmware.com
  shortDescription: cis-webhook.field.vmware.com

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: cis-webhook
spec:
  packageRef:
    refName: cis-webhook.field.vmware.com
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: cis-webhook-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
