apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cis-service.fling.vsphere.vmware.com.1.0.0
spec:
  refName: cis-service.fling.vsphere.vmware.com
  releasedAt: "2025-04-25T18:22:22Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/warroyo/cis-service@sha256:1429bf89a3fd100028837de3b2b0670f53305095267b1e6322eb8ea5f318a82e
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        cis_webhook_package:
          default: ghcr.io/warroyo/cis-webhook@sha256:cbc2818fb899adae37fafc7aac32bd37d4e27012ffe7481c4bafc58600f4f709
          type: string
        cis_webhook_version:
          default: 1.0.0
          type: string
        namespace:
          default: cis-service
          type: string
        python_image:
          default: python:3.9
          type: string
      type: object
  version: 1.0.0
