apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  annotations:
    kapp.k14s.io/delete-strategy: orphan
  creationTimestamp: null
  name: cis-webhook.field.vmware.com
spec:
  displayName: cis-webhook
  longDescription: cis-webhook.field.vmware.com
  shortDescription: cis-webhook.field.vmware.com

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    kapp.k14s.io/delete-strategy: orphan
  creationTimestamp: null
  name: cis-webhook.field.vmware.com.1.0.0
spec:
  refName: cis-webhook.field.vmware.com
  releasedAt: "2025-04-25T18:22:19Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/warroyo/cis-webhook@sha256:cbc2818fb899adae37fafc7aac32bd37d4e27012ffe7481c4bafc58600f4f709
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      default: null
      nullable: true
  version: 1.0.0
